examplesite/examplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

examplesite/main/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

app_name = "main"

urlpatterns = [
    path('',views.HomePageView.as_view(),name="home" ),
    path('leguage/<pk>', views.LeaguageDetailView.as_view(), name='leaguage_detail'),
    
    path("club/<pk>", views.ClubDetailView.as_view(), name='club_detail'),
    path("player/<pk>", views.PlayerDetailView.as_view(), name='player_detail'),
    
    # FILTER 
    path('filter/position',views.filter_by_position, name='filter_by_position' ),
    path('filter/age',views.filter_by_age, name='filter_by_age' ),
    ]


# views - asosiy logika 
# controller method  - def 
# controller class - class 

examplesite/main/models.py
import datetime
from django.db import models

# Create your models here.
class Leaguage(models.Model): 
    name = models.CharField("Liga yoki Chempionat nomi",max_length=250)
    logo = models.ImageField(upload_to="leaguage/logos/")
    country = models.CharField("Davlat", max_length=100)
    
    def __str__(self):
        return str(self.name)

class Club(models.Model):
    name = models.CharField("Klub nomi",max_length=250)
    logo = models.ImageField(upload_to="club/logos/")
    country = models.CharField("Davlat", max_length=100)
    coach = models.CharField("Trener", max_length=100)
    leaguage = models.ForeignKey(Leaguage,on_delete=models.PROTECT)
    
    def __str__(self):
        return str(self.name)

POS = (
    ('gk','Darvozabon'),
    ('df','Himoyachi'),
    ('md','Yarim himoyachi'),
    ('fw','Hujumkor himoyachi'),
    ('st','Hujumchi'),
)

class Player(models.Model):
    name = models.CharField("Ism-Sharif",max_length=250)
    image = models.ImageField(upload_to="players/images/")
    date_of_birth = models.DateField("Tugilgan sanasi")
    country = models.CharField("Davlat", max_length=100)
    club = models.ForeignKey(Club,on_delete=models.PROTECT)
    position = models.CharField(max_length=100,choices=POS)
    transfer_summa = models.PositiveIntegerField(default=0)
    height = models.PositiveSmallIntegerField(default=0)
    weight = models.PositiveSmallIntegerField(default=0)
    
    def get_age(self):
        current_year = datetime.datetime.now().year
        age = current_year - self.date_of_birth.year 
        return age
    
    def __str__(self):
        return str(self.name)
    

examplesite/main/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic import ListView ,DetailView
from .models import Club,Leaguage,Player
# Create your views here.

# TemplateView - oddiy htmlni response sifatida qaytarish
# ListView - korsatilgan modeldan ma'lumotlarn olib korsatilgan html ga "object_list" keyida jonatadi

class HomePageView(ListView):
    model = Leaguage
    # context_object_name = "ligalar"
    template_name = "index.html"
    
    # htmlga jonatiladigan ma'lumotlarni boshqarish metodi 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clubs"] = Club.objects.all()
        context["players"] = Player.objects.all() # barcha objectlarni olish
        
        # first_player = Player.objects.get(id=1) # faqat 1 ta object
        # print(first_player)
        # first_player = Player.objects.get(id=1) # faqat 1 ta object
        # print(first_player)
        # get_or_cretae_player = Player.objects.get_or_create() # 1 ta object olish yoki hosil qilish
        # __exact - aniq yozilgan matn boyicha filter
        # __iexact - aniq yozilgan matn boyicha filter katta yoki kichkina harf farqi yoq
        # __contains - berilgan matn maydonda mavjud yoki yoqligiga tekshirish
        # __icontains - berilgan matn maydonda mavjud yoki yoqligiga tekshirish katta yoki kichkina harf farqi yoq
        # __gt - katta
        # __gte - katta yoki teng 
        # __lt - kichik 
        # __lte - kichik yoki teng
        # __stratswith - berilgan matn bilan boshlansa 
        # __istratswith - berilgan matn bilan boshlansa katta yoki kichkina harf farqi yoq
        # __endswith - berilgan matn bilan tugasa 
        # __iendswith - berilgan matn bilan tugasa katta yoki kichkina harf farqi yoq
        # __range - ma'lum bir diapazondagilarni filterlash
        # filtering_players = Player.objects.filter(height__range=(150,180))
        # for p in filtering_players:
        #     print(p.name)
        #     print(p.height)
        # import datetime
        # date = datetime.date.today()
        # this_week = date - datetime.timedelta(date.weekday())
        # players_of_this_week = Player.objects.filter(created_at__in=this_week)
        # print(players_of_this_week)
        # __in - berilgan qiymatlarga mos objectlarni filterlash
        # players_of_same_country = Player.objects.filter(country__in=["Angliya","Braziliya"])
        # print(players_of_same_country)
        
        # players_all_not_english = Player.objects.all().exclude(country="Angliya")
        # print(players_all_not_english)
        altay = Player.objects.get(name="Altay Bayındır")
        # update 
        # altay.name = "Altay Bayındırjon"
        # altay.save()
        # delete 
        # altay.delete() 
        # new_club = Club.objects.create(name="Atletik" .... )
        
        # CRUD - Create , Retrive, Update , Delete 
        return context
    

class LeaguageDetailView(DetailView):
    model = Leaguage
    template_name = "leaguage.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # self.object - DetailView orqal modeldan olinayotgan obyekt
        context["clubs"] = Club.objects.filter(leaguage=self.object)

        return context
  
class ClubDetailView(DetailView):
    model = Club
    template_name = "club.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # self.object - DetailView orqal modeldan olinayotgan obyekt
        context["players"] = Player.objects.filter(club=self.object)

        return context


class PlayerDetailView(DetailView):
    model = Player
    template_name = 'player.html'
    
    



class CantactPageView(TemplateView):
    template_name = "contact.html"
    
    

def filter_by_position(request):
    if request.method  == "POST":
        pos = request.POST.get("position")
        players = Player.objects.filter(position=pos)
        data = {
            "players":players
        }
    return render(request, 'result.html', context=data)


def filter_by_age(request):
    if request.method  == "POST":
        min_age_range = request.POST.get("min_age")
        max_age_range = request.POST.get("max_age")
        players = Player.objects.filter(date_of_birth__range=[min_age_range,max_age_range])
        data = {
            "players":players
        }
    return render(request, 'result.html', context=data)

examplesite/templates/club.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark" />
    <!--<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
  /> -->
  <link rel="stylesheet" href="{% static 'css/pico.min.css' %}">
    <title>Club</title>
  </head>
  <body>
    <main class="container">
      <section class="main-data">
        <h4>
            <img src="{{object.logo.url}}" width="100" alt="">
            {{object.name}}
        </h4>
        <table border="1">
            {% for player in players %}
            <tr>
              <td>
                <a href="{% url 'main:player_detail' player.id %}">
                  <img src="{{player.image.url}}" width="100" alt="">
                  {{player.name}}
                </a>
              </td>
            </tr>
            {% endfor %}
          </table>

      </section>
    </main>
  </body>
</html>

examplesite/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark" />
  <!--<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
  /> -->
  <link rel="stylesheet" href="{% static 'css/pico.min.css' %}">
  <title>Hello world!</title>
</head>

<body>
  <br>
  <br>
  <main class="container">
    <section class="main-data">
      <div class="container">
        <div class="filter grid">
          <div class="item">
            <form action="{% url 'main:filter_by_position' %}" method="post">
              {% csrf_token %}
              <label for="positions">Choose a position:</label>
              <select name="position" id="positions">
                <option value="gk">Darvozabon</option>
                <option value="df">Himoyachi</option>
                <option value="md">Yarim himoyachi</option>
                <option value="fw">Hujumkor himoyachi</option>
                <option value="st">Hujumchi</option>
              </select>
              <input type="submit" value="Filter">
            </form>
          </div>
          <div class="item">
            <form action="{% url 'main:filter_by_age' %}" method="post">
              {% csrf_token %}
              <input type="date" name="min_age" >
              <input type="date" name="max_age" >
              <input type="submit" value="Filter">
            </form>
          </div>
          <div class="item">2</div>
          <div class="item">3</div>
        </div>
        <br>
        <hr>
        <h3>Leaguages</h3>
        <table border="1">
          {% for league in object_list %}
          <tr>
            <td>
              <a href="{% url 'main:leaguage_detail' league.id %}">
                <img src="{{league.logo.url}}" width="100" alt="">
                {{league.name}}
              </a>
            </td>
          </tr>
          {% endfor %}
        </table>
        <table border="1">
          {% for club in clubs %}
          <tr>
            <td>
              <a href="">
                <img src="{{club.logo.url}}" width="100" alt="">
                {{club.name}}
              </a>
            </td>
          </tr>
          {% endfor %}
        </table>
        <table border="1">
          {% for player in players %}
          <tr>
            <td>
              <a href="">
                <img src="{{player.image.url}}" width="100" alt="">
                {{player.name}}
              </a>
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </section>
  </main>
</body>

</html>

examplesite/templates/leaguage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark" />
    <!--<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
  /> -->
  <link rel="stylesheet" href="{% static 'css/pico.min.css' %}">
    <title>Hello world!</title>
  </head>
  <body>
    <main class="container">
      <section class="main-data">
        <h4>
            <img src="{{object.logo.url}}" width="100" alt="">
            {{object.name}}
        </h4>
        <table border="1">
            {% for club in clubs %}
            <tr>
              <td>
                <a href="">
                  <img src="{{club.logo.url}}" width="100" alt="">
                  {{club.name}}
                </a>
              </td>
            </tr>
            {% endfor %}
          </table>

      </section>
    </main>
  </body>
</html>

examplesite/templates/player.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark" />
    <!--<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
  /> -->
  <link rel="stylesheet" href="{% static 'css/pico.min.css' %}">
    <title>Player</title>
  </head>
  <body>
    <main class="container">
      <section class="main-data">
        <h4>
            <img src="{{object.image.url}}" width="100" alt="">
            {{object.name}}
        </h4>
        <h5><strong>Davlati : </strong>{{object.country}}</h5>
        <h5><strong>Tug'ilgan : </strong>{{object.date_of_birth}}</h5>
        <h5><strong>Yoshi : </strong>{{object.get_age}}</h5>
        <h5><strong>Transfer narxi : </strong>{{object.transfer_summa}}</h5>
        <h5><strong>Pozitsiyasi : </strong>
          {% if object.position == 'gk' %}
          Darvozabon
          {% elif object.position == 'df' %}
          Himoyachi
          {% elif object.position == 'md' %}
          Yarim himoyachi
          {% elif object.position == 'fw' %}
          Hujumkor himoyachi
          {% elif object.position == 'st' %}
          Hujumchi
          {% endif %}
          
          <span></span>
        </h5>
        <h5><strong>Bo'yi : </strong>{{object.height}}</h5>
        <h5><strong>Vazni : </strong>{{object.weight}}</h5>

      </section>
    </main>
  </body>
</html>

examplesite/templates/result.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark" />
  <!--<link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
  /> -->
  <link rel="stylesheet" href="{% static 'css/pico.min.css' %}">
  <title>Hello world!</title>
</head>

<body>
  <main class="container">
    <section class="result-data">
        <table border="1">
            {% for player in players %}
            <tr>
                <td>
                    <img src="{{player.image.url}}" width="100" alt="">
                </td>
                <td>{{player.name}}</td>
                <td>{{player.club}}</td>
                <td>{{player.position}}</td>
                <td>{{player.get_age}}</td>
                <td>{{player.country}}</td>
            </tr>
            {% empty %}
            No data !
            <a href="/">Go to home</a>
            {% endfor %}
        </table>
    </section>
  </main>
</body>

</html>