config/blog/urls.py
from django.urls import path
from .import views

app_name = "blog"

urlpatterns = [
    path("", views.HomePageView.as_view(), name='home')
]

config/config/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls", namespace='blog')),
    path("users/", include("users.urls", namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import * # standart login sahifasi views

from .import views


app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="auth/login.html"), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    
    path("register/",views.register, name='register'),
    path("password_change/",PasswordChangeView.as_view(
        template_name="auth/password_change_form.html",
        success_url="/"
        ), name='password_change'),
    
    path("password-reset/", PasswordResetView.as_view(
        template_name="auth/password_reset_form.html",
        email_template_name="auth/password_reset_email.html",
        html_email_template_name="auth/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),
    
    path("password-reset/done/", PasswordResetDoneView.as_view(
        template_name="auth/password_reset_done.html"), name='password_reset_done'),
    
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(
        template_name="auth/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    
    path("password-reset/complete/", PasswordResetCompleteView.as_view(
        template_name="auth/password_reset_complete.html"), name='password_reset_complete'),
    
    path("profile/<pk>", views.ProfileDetailView.as_view(), name='profile'),
    
    path("profile/edit/<pk>", views.ProfileUpdateView.as_view(), name='profile_update')
    
    
    
]

config/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
# Create your models here.

GENDERS = (
    ("male","Male"),
    ("female","Female"),
)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(upload_to="users_images/", blank=True)
    bio = models.TextField(blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=100,choices=GENDERS, blank=True)
    country = CountryField()
    
    def __str__(self):
        return self.user.username
    

config/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserRegisterForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username","first_name","email","password1","password2"]

        
import telebot

bot.send_message('-22222' ,message)

config/blog/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin # userni auth qildi qimadi tekshiradi
# Create your views here.


class HomePageView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        # print(self.request.path)
        # print(self.request.get_full_path())
        # print(self.request.get_host())
        # print(self.request.get_port())
        # print(dir(self.request.user))
        # print(self.request.user.is_authenticated)
        return super().get_context_data(**kwargs)

config/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login
from django.views.generic import DetailView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserRegisterForm
from .models import Profile
# Create your views here.


def register(request):
    form = CustomUserRegisterForm()
    if request.method == "POST":
        form = CustomUserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user) # yangi profil ochish va uni userga biriktirish
            login(request,user) # auth usermi login qilish
            return redirect("/")
        else:
            print("Error")
            return render(request, "auth/register.html")
    return render(request, "auth/register.html", context={"form":form})

class ProfileDetailView(LoginRequiredMixin,DetailView):
    model = Profile
    template_name = 'auth/profile.html'

# UpdateView - korsatilgan model objectnini bittasini alohida sahifada update qilish imkonini beradi 
class ProfileUpdateView(UpdateView):
    model = Profile
    template_name = "auth/profile_form.html"
    # fields = "__all__"  # modelni hamma maydoni forma bolib chiqadi
    fields = ["image","bio","date_of_birth", "gender", "country"] 
    # yoki shu tarzda istalgan maydonlarnigina forma qilish mumkin
    
    # hamma ishlar bajarilib muvafaqiyatli ortga qaytish uchun manzilni hosil qilivchi method 
    def get_success_url(self):
        return reverse("users:profile", kwargs={"pk":self.object.id})

config/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/milligram.css' %}">

    <title>Home Page</title>
</head>

<body>
    <header>
        <nav class="container">
            <ul style="display: flex; gap:25px; list-style:none;" >
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}" class="link">Logout</a></li>
                <li><a href="{% url 'users:password_change' %}" class="link">Password change</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}" class="link">Login</a></li>
                <li><a href="{% url 'users:register' %}" class="link">Register</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
        <main class="container">
        <h3>Hello - 
            {% if request.user.is_authenticated %}
                {% if request.user.first_name %} 
                    <a href="{% url 'users:profile' request.user.profile.id %}">{{request.user.first_name}} </a>
                {% else %} 
                <a href="{% url 'users:profile' request.user.profile.id %}">{{request.user.username}}</a>
                {% endif %}
            {% endif %}
        </h3>
    </main>
</body>

</html>